name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    name: ${{ matrix.config.name }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2019]
    steps:
    - uses: actions/checkout@v3
      with:
        path: hl2_goap_bot
    - name: Checkout and Build project 
      uses: ./hl2_goap_bot/.github/actions/build
      with:
        repo-path: hl2_goap_bot
        
    - name: Test
      working-directory: ${{github.workspace}}/build/hl2_goap_bot
      # TODO: only run tests on linux since windows requires tier0.dll, which is only available from steam.
      if: matrix.os == 'ubuntu-22.04'      
      run: ctest -C Release
      
