on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset
defaults:
  run:
    shell: bash
jobs:
  build:
    name: ${{ matrix.config.name }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    strategy:
      matrix: 
        os: [ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.os }}      
    steps:
      - uses: actions/checkout@v2
        with:
          path: hl2_goap_bot    
      - name: Checkout and Build project 
        uses: ./hl2_goap_bot/.github/actions/build
        with:
          repo-path: hl2_goap_bot
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Copy Artifact 
        run: |
          if [ $RUNNER_OS = Linux ]
            then cp ${{github.workspace}}/build/hl2_goap_bot/my_bot.so ${{github.workspace}}/hl2_goap_bot/addons; 
          else
            cp ${{github.workspace}}/build/hl2_goap_bot/my_bot.so ${{github.workspace}}/hl2_goap_bot/addons;
          fi
      - name: Compress Release Assets
        run: pushd ${{github.workspace}}/hl2_goap_bot && tar -acf ${{github.workspace}}/hl2_goap_bot.zip addons && popd
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ${{github.workspace}}/hl2_goap_bot.zip
          asset_name: hl2_goap_bot_${{ matrix.os }}.zip
          asset_content_type: application/zip
